import type { Metadata } from 'next'
import { Montserrat as FontSans } from 'next/font/google'
import './globals.css'
// import { Inter as FontSans } from 'next/font/google'
import { cn } from '@/lib/utils'
import { ThemeProvider } from './components/theme-provider'
import NavBar from './components/navbar/navbar'

// const inter = Inter({ subsets: ['latin'] })

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans'
})

export const metadata: Metadata = {
	title: 'Helldive Haven',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='dark'>
			<body
				className={cn(
					'min-h-screen font-sans antialiased bg-[#121212]',
					// bg-[#212121]
					fontSans.variable
				)}
				// className={inter.className}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<header className='sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/10'>
						<NavBar />
					</header>
					<div className='max-w-[1780px] m-auto'>{children}</div>
					<footer className='mt-32'></footer>
				</ThemeProvider>
			</body>
		</html>
	)
}
